test_boolean_assignment_value_mismatch_xpu (__main__.NumpyTestsXPU) ... ok
test_boolean_indexing_alldims_xpu (__main__.NumpyTestsXPU) ... ok
test_boolean_indexing_onedim_xpu (__main__.NumpyTestsXPU) ... ok
test_boolean_indexing_twodim_xpu (__main__.NumpyTestsXPU) ... ok
test_boolean_indexing_weirdness_tensors_xpu (__main__.NumpyTestsXPU) ... ERROR
test_boolean_indexing_weirdness_xpu (__main__.NumpyTestsXPU) ... ERROR
test_boolean_list_indexing_xpu (__main__.NumpyTestsXPU) ... ok
test_boolean_shape_mismatch_xpu (__main__.NumpyTestsXPU) ... /home/gta/xunsongh/ipex-gpu/tests/gpu/pytorch/test_indexing.py:1336: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead. (Triggered internally at  /home/gta/xunsongh/ipex-gpu/csrc/aten/operators/IndexingUtils.h:39.)
  self.assertRaisesRegex(IndexError, 'mask', lambda: arr[index])
/home/gta/xunsongh/ipex-gpu/tests/gpu/pytorch/test_indexing.py:1337: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead. (Triggered internally at  /home/gta/xunsongh/ipex-gpu/csrc/aten/operators/IndexingUtils.h:39.)
  self.assertRaisesRegex(IndexError, 'mask', lambda: arr[(slice(None), index)])
ok
test_broadcast_subspace_xpu (__main__.NumpyTestsXPU) ... ok
test_broaderrors_indexing_xpu (__main__.NumpyTestsXPU) ... ERROR
test_ellipsis_index_xpu (__main__.NumpyTestsXPU) ... ok
test_empty_fancy_index_xpu (__main__.NumpyTestsXPU) ... FAIL
test_empty_tuple_index_xpu (__main__.NumpyTestsXPU) ... ok
test_everything_returns_views_xpu (__main__.NumpyTestsXPU) ... ok
test_index_is_larger_xpu (__main__.NumpyTestsXPU) ... ok
test_index_no_floats_xpu (__main__.NumpyTestsXPU) ... ok
test_none_index_xpu (__main__.NumpyTestsXPU) ... ok
test_single_bool_index_xpu (__main__.NumpyTestsXPU) ... ok
test_single_int_index_xpu (__main__.NumpyTestsXPU) ... ok
test_trivial_fancy_out_of_bounds_xpu (__main__.NumpyTestsXPU) ... skipped 'XPU asserts instead of raising an exception'

======================================================================
ERROR: test_boolean_indexing_weirdness_tensors_xpu (__main__.NumpyTestsXPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1396, in wrapper
    method(*args, **kwargs)
  File "/home/gta/xunsongh/ipex-gpu/tests/gpu/pytorch/common/pytorch_test_base.py", line 402, in instantiated_test
    raise rte
  File "/home/gta/xunsongh/ipex-gpu/tests/gpu/pytorch/common/pytorch_test_base.py", line 397, in instantiated_test
    result = test(self, **param_kwargs)
  File "/home/gta/xunsongh/ipex-gpu/tests/gpu/pytorch/test_indexing.py", line 1394, in test_boolean_indexing_weirdness_tensors
    self.assertRaises(IndexError, lambda: a[false, [0, 1], ...])
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1985, in assertRaises
    return context.handle('assertRaises', args, kwargs)  # type: ignore[union-attr]
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/unittest/case.py", line 201, in handle
    callable_obj(*args, **kwargs)
  File "/home/gta/xunsongh/ipex-gpu/tests/gpu/pytorch/test_indexing.py", line 1394, in <lambda>
    self.assertRaises(IndexError, lambda: a[false, [0, 1], ...])
RuntimeError: shape mismatch: indexing tensors could not be broadcast together with shapes [0], [2]

======================================================================
ERROR: test_boolean_indexing_weirdness_xpu (__main__.NumpyTestsXPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1396, in wrapper
    method(*args, **kwargs)
  File "/home/gta/xunsongh/ipex-gpu/tests/gpu/pytorch/common/pytorch_test_base.py", line 402, in instantiated_test
    raise rte
  File "/home/gta/xunsongh/ipex-gpu/tests/gpu/pytorch/common/pytorch_test_base.py", line 397, in instantiated_test
    result = test(self, **param_kwargs)
  File "/home/gta/xunsongh/ipex-gpu/tests/gpu/pytorch/test_indexing.py", line 1385, in test_boolean_indexing_weirdness
    self.assertRaises(IndexError, lambda: a[False, [0, 1], ...])
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1985, in assertRaises
    return context.handle('assertRaises', args, kwargs)  # type: ignore[union-attr]
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/unittest/case.py", line 201, in handle
    callable_obj(*args, **kwargs)
  File "/home/gta/xunsongh/ipex-gpu/tests/gpu/pytorch/test_indexing.py", line 1385, in <lambda>
    self.assertRaises(IndexError, lambda: a[False, [0, 1], ...])
RuntimeError: shape mismatch: indexing tensors could not be broadcast together with shapes [0], [2]

======================================================================
ERROR: test_broaderrors_indexing_xpu (__main__.NumpyTestsXPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1396, in wrapper
    method(*args, **kwargs)
  File "/home/gta/xunsongh/ipex-gpu/tests/gpu/pytorch/common/pytorch_test_base.py", line 402, in instantiated_test
    raise rte
  File "/home/gta/xunsongh/ipex-gpu/tests/gpu/pytorch/common/pytorch_test_base.py", line 397, in instantiated_test
    result = test(self, **param_kwargs)
  File "/home/gta/xunsongh/ipex-gpu/tests/gpu/pytorch/test_indexing.py", line 1425, in test_broaderrors_indexing
    self.assertRaisesRegex(IndexError, 'shape mismatch', a.__getitem__, ([0, 1], [0, 1, 2]))
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1998, in assertRaisesRegex
    return context.handle('assertRaisesRegex', args, kwargs)  # type: ignore[attr-defined]
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/unittest/case.py", line 201, in handle
    callable_obj(*args, **kwargs)
RuntimeError: shape mismatch: indexing tensors could not be broadcast together with shapes [2], [3]

======================================================================
FAIL: test_empty_fancy_index_xpu (__main__.NumpyTestsXPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1396, in wrapper
    method(*args, **kwargs)
  File "/home/gta/xunsongh/ipex-gpu/tests/gpu/pytorch/common/pytorch_test_base.py", line 397, in instantiated_test
    result = test(self, **param_kwargs)
  File "/home/gta/xunsongh/ipex-gpu/tests/gpu/pytorch/test_indexing.py", line 1277, in test_empty_fancy_index
    self.assertRaises(IndexError, lambda: a[b])
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1985, in assertRaises
    return context.handle('assertRaises', args, kwargs)  # type: ignore[union-attr]
AssertionError: IndexError not raised by <lambda>

----------------------------------------------------------------------
Ran 20 tests in 3.858s

FAILED (failures=1, errors=3, skipped=1)
Raised CalledProcessError: return code 1.