MESA: warning: Driver does not support the 0xbd5 PCI ID.
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
test_normal_std_error_xpu_xpu (__main__.TestRandomTensorCreationXPU) ... ok
test_normal_xpu_xpu_float32 (__main__.TestRandomTensorCreationXPU) ... ok
test_normal_xpu_xpu_float64 (__main__.TestRandomTensorCreationXPU) ... FAIL
test_rand_xpu_xpu_complex128 (__main__.TestRandomTensorCreationXPU) ... skipped 'dtype not support on XPU'
test_rand_xpu_xpu_complex32 (__main__.TestRandomTensorCreationXPU) ... skipped 'dtype not support on XPU'
test_rand_xpu_xpu_complex64 (__main__.TestRandomTensorCreationXPU) ... skipped 'dtype not support on XPU'
test_rand_xpu_xpu_float32 (__main__.TestRandomTensorCreationXPU) ... FAIL
test_rand_xpu_xpu_float64 (__main__.TestRandomTensorCreationXPU) ... FAIL
test_randint_inference_xpu_xpu (__main__.TestRandomTensorCreationXPU) ... skipped 'Only runs on cpu'
test_randint_xpu_xpu (__main__.TestRandomTensorCreationXPU) ... skipped 'Only runs on cpu'
test_randn_xpu_xpu_bfloat16 (__main__.TestRandomTensorCreationXPU) ... FAIL
test_randn_xpu_xpu_complex128 (__main__.TestRandomTensorCreationXPU) ... skipped 'dtype not support on XPU'
test_randn_xpu_xpu_complex32 (__main__.TestRandomTensorCreationXPU) ... skipped 'dtype not support on XPU'
test_randn_xpu_xpu_complex64 (__main__.TestRandomTensorCreationXPU) ... skipped 'dtype not support on XPU'
test_randn_xpu_xpu_float16 (__main__.TestRandomTensorCreationXPU) ... FAIL
test_randn_xpu_xpu_float32 (__main__.TestRandomTensorCreationXPU) ... FAIL
test_randn_xpu_xpu_float64 (__main__.TestRandomTensorCreationXPU) ... FAIL
test_random_neg_values_xpu_xpu (__main__.TestRandomTensorCreationXPU) ... ok
test_randperm_device_compatibility_xpu_xpu (__main__.TestRandomTensorCreationXPU) ... skipped 'not ready on XPU'
test_randperm_xpu_xpu (__main__.TestRandomTensorCreationXPU) ... FAIL
test_uniform_from_to_xpu_xpu_bfloat16 (__main__.TestRandomTensorCreationXPU) ... ok
test_uniform_from_to_xpu_xpu_float16 (__main__.TestRandomTensorCreationXPU) ... ok
test_uniform_from_to_xpu_xpu_float32 (__main__.TestRandomTensorCreationXPU) ... ok
test_uniform_from_to_xpu_xpu_float64 (__main__.TestRandomTensorCreationXPU) ... ok

======================================================================
FAIL: test_normal_xpu_xpu_float64 (__main__.TestRandomTensorCreationXPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 2004, in wrapper
    method(*args, **kwargs)
  File "/home/gta/xunsongh/ipex-gpu/tests/gpu/experimental/common/pytorch_test_base.py", line 430, in instantiated_test
    result = test(self, **param_kwargs)
  File "/home/gta/xunsongh/ipex-gpu/tests/gpu/experimental/test/test_tensor_creation_ops.py", line 2321, in test_normal
    helper(self, device, dtype, lambda x: x, lambda t: t, lambda mean: mean)
  File "/home/gta/xunsongh/ipex-gpu/tests/gpu/experimental/test/test_tensor_creation_ops.py", line 2219, in helper
    self.assertEqual(t_transform(q[99:100]).mean(), 0, atol=0.2, rtol=0)
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 2468, in assertEqual
    assert_equal(
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/site-packages/torch/testing/_comparison.py", line 1093, in assert_equal
    raise error_metas[0].to_error(msg)
AssertionError: Scalars are not close!

Absolute difference: 0.22496423454074282 (up to 0.2 allowed)
Relative difference: inf (up to 0 allowed)

======================================================================
FAIL: test_rand_xpu_xpu_float32 (__main__.TestRandomTensorCreationXPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 2004, in wrapper
    method(*args, **kwargs)
  File "/home/gta/xunsongh/ipex-gpu/tests/gpu/experimental/common/pytorch_test_base.py", line 430, in instantiated_test
    result = test(self, **param_kwargs)
  File "/home/gta/xunsongh/ipex-gpu/tests/gpu/experimental/test/test_tensor_creation_ops.py", line 2448, in test_rand
    self.assertEqual(res1, res2)
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 2468, in assertEqual
    assert_equal(
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/site-packages/torch/testing/_comparison.py", line 1093, in assert_equal
    raise error_metas[0].to_error(msg)
AssertionError: Tensor-likes are not close!

Mismatched elements: 9980 / 10000 (99.8%)
Greatest absolute difference: 0.9832078237086535 at index (4, 73) (up to 0.001 allowed)
Greatest relative difference: 7171.088027581261 at index (48, 43) (up to 1.3e-06 allowed)

======================================================================
FAIL: test_rand_xpu_xpu_float64 (__main__.TestRandomTensorCreationXPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 2004, in wrapper
    method(*args, **kwargs)
  File "/home/gta/xunsongh/ipex-gpu/tests/gpu/experimental/common/pytorch_test_base.py", line 430, in instantiated_test
    result = test(self, **param_kwargs)
  File "/home/gta/xunsongh/ipex-gpu/tests/gpu/experimental/test/test_tensor_creation_ops.py", line 2448, in test_rand
    self.assertEqual(res1, res2)
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 2468, in assertEqual
    assert_equal(
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/site-packages/torch/testing/_comparison.py", line 1093, in assert_equal
    raise error_metas[0].to_error(msg)
AssertionError: Tensor-likes are not close!

Mismatched elements: 9975 / 10000 (99.8%)
Greatest absolute difference: 0.9944094135055717 at index (37, 56) (up to 0.001 allowed)
Greatest relative difference: 1224.0143097810874 at index (18, 18) (up to 1e-07 allowed)

======================================================================
FAIL: test_randn_xpu_xpu_bfloat16 (__main__.TestRandomTensorCreationXPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 2004, in wrapper
    method(*args, **kwargs)
  File "/home/gta/xunsongh/ipex-gpu/tests/gpu/experimental/common/pytorch_test_base.py", line 430, in instantiated_test
    result = test(self, **param_kwargs)
  File "/home/gta/xunsongh/ipex-gpu/tests/gpu/experimental/test/test_tensor_creation_ops.py", line 2437, in test_randn
    self.assertEqual(res1, res2)
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 2468, in assertEqual
    assert_equal(
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/site-packages/torch/testing/_comparison.py", line 1093, in assert_equal
    raise error_metas[0].to_error(msg)
AssertionError: Tensor-likes are not close!

Mismatched elements: 9961 / 10000 (99.6%)
Greatest absolute difference: 5.3828125 at index (53, 77) (up to 0.001 allowed)
Greatest relative difference: 2047.0 at index (65, 47) (up to 0.016 allowed)

======================================================================
FAIL: test_randn_xpu_xpu_float16 (__main__.TestRandomTensorCreationXPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 2004, in wrapper
    method(*args, **kwargs)
  File "/home/gta/xunsongh/ipex-gpu/tests/gpu/experimental/common/pytorch_test_base.py", line 430, in instantiated_test
    result = test(self, **param_kwargs)
  File "/home/gta/xunsongh/ipex-gpu/tests/gpu/experimental/test/test_tensor_creation_ops.py", line 2437, in test_randn
    self.assertEqual(res1, res2)
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 2468, in assertEqual
    assert_equal(
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/site-packages/torch/testing/_comparison.py", line 1093, in assert_equal
    raise error_metas[0].to_error(msg)
AssertionError: Tensor-likes are not close!

Mismatched elements: 9987 / 10000 (99.9%)
Greatest absolute difference: 5.673828125 at index (22, 31) (up to 0.001 allowed)
Greatest relative difference: 3731.9633911368014 at index (78, 72) (up to 0.001 allowed)

======================================================================
FAIL: test_randn_xpu_xpu_float32 (__main__.TestRandomTensorCreationXPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 2004, in wrapper
    method(*args, **kwargs)
  File "/home/gta/xunsongh/ipex-gpu/tests/gpu/experimental/common/pytorch_test_base.py", line 430, in instantiated_test
    result = test(self, **param_kwargs)
  File "/home/gta/xunsongh/ipex-gpu/tests/gpu/experimental/test/test_tensor_creation_ops.py", line 2437, in test_randn
    self.assertEqual(res1, res2)
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 2468, in assertEqual
    assert_equal(
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/site-packages/torch/testing/_comparison.py", line 1093, in assert_equal
    raise error_metas[0].to_error(msg)
AssertionError: Tensor-likes are not close!

Mismatched elements: 9995 / 10000 (100.0%)
Greatest absolute difference: 6.135540246963501 at index (2, 97) (up to 0.001 allowed)
Greatest relative difference: 1905.7988985792606 at index (35, 80) (up to 1.3e-06 allowed)

======================================================================
FAIL: test_randn_xpu_xpu_float64 (__main__.TestRandomTensorCreationXPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 2004, in wrapper
    method(*args, **kwargs)
  File "/home/gta/xunsongh/ipex-gpu/tests/gpu/experimental/common/pytorch_test_base.py", line 430, in instantiated_test
    result = test(self, **param_kwargs)
  File "/home/gta/xunsongh/ipex-gpu/tests/gpu/experimental/test/test_tensor_creation_ops.py", line 2437, in test_randn
    self.assertEqual(res1, res2)
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 2468, in assertEqual
    assert_equal(
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/site-packages/torch/testing/_comparison.py", line 1093, in assert_equal
    raise error_metas[0].to_error(msg)
AssertionError: Tensor-likes are not close!

Mismatched elements: 9992 / 10000 (99.9%)
Greatest absolute difference: 5.176687787952412 at index (51, 29) (up to 0.001 allowed)
Greatest relative difference: 24527.087140360614 at index (65, 69) (up to 1e-07 allowed)

======================================================================
FAIL: test_randperm_xpu_xpu (__main__.TestRandomTensorCreationXPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 2004, in wrapper
    method(*args, **kwargs)
  File "/home/gta/xunsongh/ipex-gpu/tests/gpu/experimental/common/pytorch_test_base.py", line 430, in instantiated_test
    result = test(self, **param_kwargs)
  File "/home/gta/xunsongh/ipex-gpu/tests/gpu/experimental/test/test_tensor_creation_ops.py", line 2463, in test_randperm
    with torch.random.fork_rng(devices=rng_device):
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/site-packages/torch/random.py", line 122, in fork_rng
    gpu_rng_states.append(torch.cuda.get_rng_state(device))
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/site-packages/torch/cuda/random.py", line 22, in get_rng_state
    _lazy_init()
  File "/home/gta/miniconda3/envs/xunsongh/lib/python3.9/site-packages/torch/cuda/__init__.py", line 221, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

----------------------------------------------------------------------
Ran 24 tests in 1.670s

FAILED (failures=8, skipped=9)
Raised CalledProcessError: return code 1.